# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: nuxeo-svc
  namespace: development
  labels:
    k8s-app: nuxeo-svc
spec:
  ports:
    - name: nuxeo-svc
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    k8s-app: nuxeo
  type: ClusterIP
  sessionAffinity: None
