# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxeo-nginx
  namespace: development
  labels:
    k8s-app: nuxeo-nginx
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nuxeo-nginx
  template:
    metadata:
      labels:
        k8s-app: nuxeo-nginx
    spec:
      volumes:
        - name: nuxeo-config-nginx
          configMap:
            name: nuxeo-config-nginx
            defaultMode: 420
      containers:
        - name: nuxeo-nginx
          image: docker.packages.nuxeo.com/nuxeo/nginx-centos7:0.0.1
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: nuxeo-config-nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
