# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: nuxeo-ui-svc
  namespace: development
  labels:
    k8s-app: nuxeo-ui-svc
spec:
  ports:
    - name: nuxeo-ui-svc
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    k8s-app: nuxeo-ui
  type: ClusterIP
  sessionAffinity: None
