# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: nuxeo-proxy-svc
  namespace: development
  labels:
    k8s-app: nuxeo-proxy-svc
spec:
  ports:
    - name: nuxeo-proxy-svc
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    k8s-app: nuxeo-nginx
  type: ClusterIP
  sessionAffinity: None
