apiVersion: v1
entries:
  apm-server:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2024-07-29T13:28:07.9930675+02:00"
    description: Official Elastic helm chart for Elastic APM Server
    digest: 3401a23adaef389193fd07df2be4bb56f70c53ba31a88f56d8d7b45f98d1bc06
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/apm.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: apm-server
    sources:
    - https://github.com/elastic/apm
    urls:
    - charts/apm-server-8.5.1.tgz
    version: 8.5.1
  arangodb:
  - apiVersion: v2
    created: "2024-07-29T13:28:08.0010705+02:00"
    digest: 82b9994a25b6833e79ddf04c0573cd5146be1685bd2bb9805e93a071643bef1a
    name: arangodb
    urls:
    - charts/arangodb-1.0.0.tgz
    version: 1.0.0
  arangodb-ingress-proxy:
  - apiVersion: v1
    created: "2024-07-29T13:28:08.0083898+02:00"
    description: ArangoDB Ingress Proxy
    digest: 0576833e01d32f063f415c8a29f7fd370bc7853fe0d2d22ddbec071937702187
    name: arangodb-ingress-proxy
    urls:
    - charts/arangodb-ingress-proxy-1.0.0.tgz
    version: 1.0.0
  elasticsearch:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2024-07-29T13:28:08.0181606+02:00"
    description: Official Elastic helm chart for Elasticsearch
    digest: 89bc07d7b2de34e419c2d755274ad05916728f6d351ba8fffb9754261e17295d
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/elasticsearch.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: elasticsearch
    sources:
    - https://github.com/elastic/elasticsearch
    urls:
    - charts/elasticsearch-8.5.1.tgz
    version: 8.5.1
  grafana:
  - annotations:
      artifacthub.io/license: AGPL-3.0-only
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/grafana/helm-charts
        - name: Upstream Project
          url: https://github.com/grafana/grafana
    apiVersion: v2
    appVersion: 10.0.3
    created: "2024-07-29T13:28:08.0271581+02:00"
    description: The leading tool for querying and visualizing time series and metrics.
    digest: 9ec01d63079ad71146126479deff17bdb5e6b8859edf79d3fb9be0833acf4a12
    home: https://grafana.net
    icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
    keywords:
    - monitoring
    - metric
    kubeVersion: ^1.8.0-0
    maintainers:
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rluckie@cisco.com
      name: rtluckie
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: mail@torstenwalter.de
      name: torstenwalter
    name: grafana
    sources:
    - https://github.com/grafana/grafana
    - https://github.com/grafana/helm-charts
    type: application
    urls:
    - charts/grafana-6.58.8.tgz
    version: 6.58.8
  infra-chart:
  - apiVersion: v2
    created: "2024-07-29T13:28:08.0341664+02:00"
    description: A Helm chart for installing infrastructure components for the FRMS
      system.
    digest: 93eaa2d38517292dafa20cbbe7e18d49e5d24fc9e809a0f2216a0c08b2ebe83b
    name: infra-chart
    type: application
    urls:
    - charts/infra-chart-1.0.0.tgz
    version: 1.0.0
  jenkins:
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/changes: |
        - Update `docker.io/kiwigrid/k8s-sidecar` to version `docker.io/kiwigrid/k8s-sidecar`
      artifacthub.io/images: |
        - name: jenkins
          image: docker.io/jenkins/jenkins:2.426.3-jdk17
        - name: k8s-sidecar
          image: docker.io/kiwigrid/k8s-sidecar:1.25.4
        - name: inbound-agent
          image: jenkins/inbound-agent:3206.vb_15dcf73f6a_9-3
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
        - name: Jenkins
          url: https://www.jenkins.io/
        - name: support
          url: https://github.com/jenkinsci/helm-charts/issues
    apiVersion: v2
    appVersion: 2.426.3
    created: "2024-07-29T13:28:08.0381681+02:00"
    description: Jenkins - Build great things at any scale! The leading open source
      automation server, Jenkins provides over 1800 plugins to support building, deploying
      and automating any project.
    digest: f6f0a4150c82eef9e3a05c32e5f94207231d5eb86613a61a8453fc4f8700a6e6
    home: https://jenkins.io/
    icon: https://get.jenkins.io/art/jenkins-logo/logo.svg
    keywords:
    - jenkins
    - ci
    - devops
    maintainers:
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: garridomota@gmail.com
      name: mogaal
    - email: wmcdona89@gmail.com
      name: wmcdona89
    - email: timjacomb1@gmail.com
      name: timja
    name: jenkins
    sources:
    - https://github.com/jenkinsci/jenkins
    - https://github.com/jenkinsci/docker-inbound-agent
    - https://github.com/maorfr/kube-tasks
    - https://github.com/jenkinsci/configuration-as-code-plugin
    urls:
    - charts/jenkins-5.0.13.tgz
    version: 5.0.13
  keycloak:
  - annotations:
      category: DeveloperTools
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 21.0.2
    created: "2024-07-29T13:28:08.0566938+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.x.x
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 2.x.x
    description: Keycloak is a high performance Java-based identity and access management
      solution. It lets developers add an authentication layer to their applications
      with minimum effort.
    digest: fb743e1f96fac1fbbc994d1228566905aaf972f162da1b79fcc4eabcfc8ba211
    home: https://www.keycloak.org
    icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
    keywords:
    - keycloak
    - access-management
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: keycloak
    sources:
    - https://github.com/bitnami/containers/tree/main/bitnami/keycloak
    - https://github.com/keycloak/keycloak
    urls:
    - charts/keycloak-14.2.0.tgz
    version: 14.2.0
  kibana:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2024-07-29T13:28:08.0661061+02:00"
    description: Official Elastic helm chart for Kibana
    digest: 1b92a833a6a6f2f69a255779a01ce6e334fa4b1d950403bf13d13cafc2078a73
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/kibana.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: kibana
    sources:
    - https://github.com/elastic/kibana
    urls:
    - charts/kibana-8.5.1.tgz
    version: 8.5.1
  logstash:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2024-07-29T13:28:08.0740119+02:00"
    description: Official Elastic helm chart for Logstash
    digest: f0d8a9a5f2b3111afd85289be34afbdf175e2076e2c49f4e4c158bf4fb419f22
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/logstash.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: logstash
    sources:
    - https://github.com/elastic/logstash
    urls:
    - charts/logstash-8.5.1.tgz
    version: 8.5.1
  nats:
  - apiVersion: v2
    appVersion: 2.9.19
    created: "2024-07-29T13:28:08.0810996+02:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: 7fdcabcd5f7cfa337e94fd0d9666ee83dbfed1280ec9f8096d04a53aba19908d
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - charts/nats-0.19.16.tgz
    version: 0.19.16
  nginx-ingress-controller:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 1.6.4
    created: "2024-07-29T13:28:08.0900931+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 2.x.x
    description: NGINX Ingress Controller is an Ingress controller that manages external
      access to HTTP services in a Kubernetes cluster using NGINX.
    digest: 8a33f2bd1af4e56cadb336a8c7815090085ccdbb74546098153975fbe0c6826d
    home: https://github.com/bitnami/charts/tree/main/bitnami/nginx-ingress-controller
    icon: https://bitnami.com/assets/stacks/nginx-ingress-controller/img/nginx-ingress-controller-stack-220x234.png
    keywords:
    - ingress
    - nginx
    - http
    - web
    - www
    - reverse proxy
    kubeVersion: '>= 1.20.0-0'
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: nginx-ingress-controller
    sources:
    - https://github.com/bitnami/containers/tree/main/bitnami/nginx-ingress-controller
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - charts/nginx-ingress-controller-9.3.32.tgz
    version: 9.3.32
  prometheus:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
        - name: Upstream Project
          url: https://github.com/prometheus/prometheus
    apiVersion: v2
    appVersion: v2.46.0
    created: "2024-07-29T13:28:08.1005643+02:00"
    dependencies:
    - condition: alertmanager.enabled
      name: alertmanager
      repository: https://prometheus-community.github.io/helm-charts
      version: 0.33.*
    - condition: kube-state-metrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 5.10.*
    - condition: prometheus-node-exporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.21.*
    - condition: prometheus-pushgateway.enabled
      name: prometheus-pushgateway
      repository: https://prometheus-community.github.io/helm-charts
      version: 2.4.*
    description: Prometheus is a monitoring system and time series database.
    digest: 28060bdaa968a74dcce531c06598c0e008af47c9f51e01f39d58f8b147031bd2
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    keywords:
    - monitoring
    - prometheus
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: naseem@transit.app
      name: naseemkullah
    - email: rootsandtrees@posteo.de
      name: zeritti
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    type: application
    urls:
    - charts/prometheus-23.3.0.tgz
    version: 23.3.0
  redis:
  - annotations:
      category: Database
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 7.0.9
    created: "2024-07-29T13:28:08.1129851+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 2.x.x
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: dfbb8029022045a3b73a5d18ff10cc6bb20aaab45d7d5101bd0b281575e81e23
    home: https://github.com/bitnami/charts/tree/main/bitnami/redis
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: redis
    sources:
    - https://github.com/bitnami/containers/tree/main/bitnami/redis
    urls:
    - charts/redis-17.8.5.tgz
    version: 17.8.5
  vault:
  - annotations:
      charts.openshift.io/name: HashiCorp Vault
    apiVersion: v2
    appVersion: 1.13.1
    created: "2024-07-29T13:28:08.1209847+02:00"
    description: Official HashiCorp Vault Chart
    digest: 16828261422256465670d504b31ec71f1ba59bc6a922413632c7ff54eb4b03e5
    home: https://www.vaultproject.io
    icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
    keywords:
    - vault
    - security
    - encryption
    - secrets
    - management
    - automation
    - infrastructure
    kubeVersion: '>= 1.22.0-0'
    name: vault
    sources:
    - https://github.com/hashicorp/vault
    - https://github.com/hashicorp/vault-helm
    - https://github.com/hashicorp/vault-k8s
    - https://github.com/hashicorp/vault-csi-provider
    urls:
    - charts/vault-0.24.0.tgz
    version: 0.24.0
generated: "2024-07-29T13:28:07.9854766+02:00"
