# SPDX-License-Identifier: Apache-2.0

{{- $functionNs := default .Release.Namespace .Values.functionNamespace }}
{{- if not .Values.openfaasPro }}
{{- if .Values.alertmanager.create }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: alertmanager
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: alertmanager
  namespace: openfaas
spec:
  type: ClusterIP
  ports:
    - port: 9093
      protocol: TCP
  selector:
    app: alertmanager
{{- end }}
{{- end }}
