# SPDX-License-Identifier: Apache-2.0

kind: Profile
apiVersion: openfaas.com/v1
metadata:
  name: nodeselector
  namespace: openfaas
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: infra-chart
    meta.helm.sh/release-namespace: development
    helm.sh/hook: "post-install"
depends:
  - name: profiles.openfaas.com
    kind: CustomResourceDefinition
spec:
    tolerations:
    - key: "kubernetes.io/hostname"
      operator: "Exists"
      effect: "NoSchedule"
